### PR TITLE
Check for builtin templates

### LINKED ISSUE #150: Assertion failed: class_decl && "TemplateSpecializationType is not a TplSpecDecl?"
Originally reported on Google Code with ID 150

```
I'm trying to use iwyu with http://github.com/mapbox/mapbox-gl-native on OS X 10.9.
I compiled iwyu against a clang 3.4.2 final stable.

I'm running this command:

CXX="include-what-you-use -Xiwyu --verbose=3 -isystem\"`xcode-select -p`/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1\""
make linux

and the first command gyp generates is

  include-what-you-use -Xiwyu --verbose=3 -isystem"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1"
'-DNDEBUG' -I../../include -I../Release/obj/gen/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
-fasm-blocks -mpascal-strings -O3 -mmacosx-version-min=10.9 -arch x86_64 -std=c++11
-stdlib=libc++ -fvisibility-inlines-hidden -Wall -Wextra -I/usr/local/Cellar/libpng/1.6.10/include/libpng16
-I/usr/local/include -I/Users/kkaefer/Code/gl/native/mapnik-packaging/osx/out/build-cpp11-libcpp-universal/include
-MMD -MF ../Release/.deps/../Release/obj.target/llmr-x86/src/clipper/clipper.o.d.raw
 -c -o ../Release/obj.target/llmr-x86/src/clipper/clipper.o ../../src/clipper/clipper.cpp

which fails with

/Users/kkaefer/Code/include-what-you-use/iwyu.cc:3081: Assertion failed: class_decl
&& "TemplateSpecializationType is not a TplSpecDecl?"
make[1]: *** [../Release/obj.target/llmr-x86/src/clipper/clipper.o] Abort trap: 6

```

Reported by `mail@kkaefer.com` on 2014-06-17 14:38:03

### PR DESCRIPTION
**Pull request by jru**
Fixes #150. Detail comments in the commits.

### CODE REVIEW

File: iwyu_output.cc [hunk 1]
```diff
@@ -1123,17 +1123,22 @@ void ProcessFullUse(OneUse* use,
...
+  if (GetLocation(use->decl()).isInvalid()) {
+    VERRS(6) << "Ignoring use of " << use->symbol_name() << " ("
+             << use->PrintableUseLoc() << "): built-in symbol\n";
+    use->set_ignore_use();
+    return;
+  } else if (const FunctionDecl* fn_decl = DynCastFrom(use->decl())) {
     if (StartsWith(use->symbol_name(), "__builtin_")) {
-      VERRS(6) << "Ignoring use of " << use->symbol_name()
-               << " (" << use->PrintableUseLoc() << "): built-in function\n";
+      VERRS(6) << "Ignoring use of " << use->symbol_name() << " ("
```
Comment (kimgr) [inline iwyu_output.cc]: It would make the patch easier to parse if you didn't (let clang-format) reformat these unchanged lines.

File: tests/cxx/built_ins_template.cc [hunk 2]
```diff
@@ -0,0 +1,20 @@
+//===--- built_ins_template.cc - test input file for iwyu -----------------===//
```
Comment (kimgr) [inline tests/cxx/built_ins_template.cc]: "builtins" is usually written as one word, so maybe `builtin_templates.cc` instead?

File: tests/cxx/built_ins_template.cc [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+//
+//                     The LLVM Compiler Infrastructure
+//
+// This file is distributed under the University of Illinois Open Source
+// License. See LICENSE.TXT for details.
+//
+//===----------------------------------------------------------------------===//
+
+//Built-ins have no declaration, thus they need no include.
```
Comment (kimgr) [inline tests/cxx/built_ins_template.cc]: Space after `//`

File: tests/cxx/built_ins_template.cc [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+
+__type_pack_element<0, int> t;
+
+//TODO: Ignoring use of __type_pack_element ... built-in function
```
Comment (kimgr) [inline tests/cxx/built_ins_template.cc]: Do you mean you'd like to check the IWYU output here? I wonder if it's possible at the high verbosity level it is right now... Maybe just skip the TODO.

File: iwyu.cc [hunk 5]
```diff
@@ -1045,7 +1045,9 @@ class AstFlattenerVisitor : public BaseAstVisitor<AstFlattenerVisitor> {
     NodeSet* node_set = &nodeset_decl_cache_[decl];
     if (node_set->empty()) {
       if (decl->isImplicit()) {
-        TraverseImplicitDeclHelper(dyn_cast_or_null<FunctionDecl>(decl));
+        if (FunctionDecl* func = DynCastFrom(decl)) {
```
[the remark this answers is not in the document]
Comment (jru) [reply iwyu.cc]: As far as I could find, there really is nothing to traverse, since they are not defined in the source code. 
The BuiltinTemplateDecl contains only its ID and inherits TemplateDecl things, like parameters and so on.

File: iwyu_output.cc (hunk 1 above)
Comment (jru) [reply iwyu_output.cc]: Yep. Sorry for that

File: iwyu_output.cc [hunk 6]
```diff
@@ -1123,17 +1123,22 @@ void ProcessFullUse(OneUse* use,
   // (B3) Discard symbol uses for builtin symbols, including new/delete.
   // TODO(csilvers): we could use getBuiltinID(), but it returns
   // non-zero for things like malloc.  Figure out how to use it.
-  if (const FunctionDecl* fn_decl = DynCastFrom(use->decl())) {
+  if (GetLocation(use->decl()).isInvalid()) {
```
[the remark this answers is not in the document]
Comment (jru) [reply iwyu_output.cc]: True. But, I think that template builtins are special. They are not part of that table, I think. 
I will need to look into it, but it seems that checking for the dynamic type (BuiltinTemplateDecl) could be the only certain way to tell.

File: tests/cxx/built_ins_template.cc (hunk 2 above)
Comment (jru) [reply tests/cxx/built_ins_template.cc]: I was following the convention of the other two tests: `built_ins_no_includes.cc` and `built_ins_new_included.cc`. Personally, I prefer *builtins*, should I make them all consistent?

Comment (kimgr) [reply tests/cxx/built_ins_template.cc]: Ah, I see. Let's leave it as-is for now, and we can follow up with a global rename later.

File: iwyu_output.cc [hunk 7]
```diff
@@ -1120,22 +1120,32 @@ void ProcessFullUse(OneUse* use,
...
+  // (B3) Discard symbol uses for builtin symbols, including new/delete and
+  // template builtins.
+  if (isa<clang::BuiltinTemplateDecl>(use->decl())) {
+    VERRS(6) << "Ignoring use of " << use->symbol_name() << " ("
+             << use->PrintableUseLoc() << "): built-in template\n";
+    use->set_ignore_use();
+    return;
+  } else {
+    // A compiler builtin without a predefined header file (e.g. __builtin_..)
+    auto const iden = use->decl()->getIdentifier();
```
Comment (kimgr) [inline iwyu_output.cc]: Only use `auto` if the type is clearly visible on the line (or in extreme cases like `std::map` iteration :)). I think this should say `const IdentifierInfo* iden = use->decl->getIdentifier();`

File: iwyu_output.cc [hunk 8]
```diff
@@ -1120,22 +1120,32 @@ void ProcessFullUse(OneUse* use,
...
-      VERRS(6) << "Ignoring use of " << use->symbol_name()
-               << " (" << use->PrintableUseLoc() << "): built-in new/delete\n";
+  // (B3) Discard symbol uses for builtin symbols, including new/delete and
+  // template builtins.
+  if (isa<clang::BuiltinTemplateDecl>(use->decl())) {
+    VERRS(6) << "Ignoring use of " << use->symbol_name() << " ("
+             << use->PrintableUseLoc() << "): built-in template\n";
+    use->set_ignore_use();
+    return;
+  } else {
```
Comment (kimgr) [inline iwyu_output.cc]: No need for `else` after return, here or below.

File: iwyu_output.cc [hunk 9]
```diff
@@ -1120,22 +1120,32 @@ void ProcessFullUse(OneUse* use,
...
+    // A compiler builtin without a predefined header file (e.g. __builtin_..)
+    auto const iden = use->decl()->getIdentifier();
+    if (iden && iden->getBuiltinID() != 0 &&
+        !clang::Builtin::Context::isBuiltinFunc(use->symbol_name().c_str())) {
```
Comment (kimgr) [inline iwyu_output.cc]: This looks inverted -- shouldn't the `!` go away there? And does that mean there's a missing test?

File: iwyu_output.cc [hunk 10]
```diff
@@ -1120,22 +1120,32 @@ void ProcessFullUse(OneUse* use,
...
+      VERRS(6) << "Ignoring use of " << use->symbol_name() << " ("
+               << use->PrintableUseLoc() << "): built-in function\n";
       use->set_ignore_use();
       return;
+      // Special case for operators new/delete: Only treated as built-in if they
+      // are the default, non-placement versions.
+    } else if (const FunctionDecl* fn_decl = DynCastFrom(use->decl())) {
+      const string dfn_file = GetFilePath(fn_decl);
+      if (IsDefaultNewOrDelete(fn_decl, ConvertToQuotedInclude(dfn_file))) {
```
Comment (kimgr) [inline iwyu_output.cc]: I think we should look into IsDefaultNewOrDelete and see if we can use some better technique to decide if it's placement new or not. But that can also wait for a follow-up.

File: tests/cxx/builtins_new_included.cc [hunk 11]
```diff
@@ -1,4 +1,4 @@
-//===--- built_ins_new_included.cc - test input file for iwyu -------------===//
+//===--- builtins_new_included.cc - test input file for iwyu --------------===//
```
Comment (kimgr) [inline tests/cxx/builtins_new_included.cc]: Sorry I tricked you into this :)

Can you revert for now, and we can clean it up separately? Thanks

File: iwyu.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (kimgr) [reply iwyu.cc]: Makes sense! Might be nice to add a comment to say that.

File: iwyu_output.cc (hunk 9 above)
Comment (jru) [reply iwyu_output.cc]: I think it is a misnomer since in both cases they will be functions, but if `isBuiltinFunc` returns true the function is one of the special __builtin_* that have no header or declaration anywhere. That's why I check that it has a valid builtin ID but it isn't one of this special ones. I assume that means it is then a regular libc/libm function (possibly with associated header) like malloc. That is also the reason why the comment said before that checking whether getBuiltinID returns > 0 is not enough.

For more info look in clang/Basic/Builtins.def where they are [defined](https://github.com/llvm-mirror/clang/blob/a3ba348aeea36f4cd6155854364e088bfd66d14d/include/clang/Basic/Builtins.def#L76). 'F' attribute means special builtin, 'f' means regular function. Or so I understand it :)

Ideally, I would have used `isPredefinedLibFunction` which does exactly what I want but it requires us to get hold of the *Context* object from the *CompilerInstance* somehow. I thought it wouldn't be worth it to go that route, but I am open for suggestions!

File: iwyu_output.cc (hunk 10 above)
Comment (jru) [reply iwyu_output.cc]: Yes, I agree.

File: iwyu.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (jru) [reply iwyu.cc]: After experimenting for a while (trying to make it work for other decls) I went for the TODO comment.

**Comment by jru** [comment]
Corrections done and some commits rephrased for clarity. Ready to merge if you are :)

File: iwyu.cc [hunk 12]
```diff
@@ -3306,9 +3306,18 @@ class InstantiatedTemplateVisitor
...
-    const ClassTemplateSpecializationDecl* class_decl
-        = DynCastFrom(TypeToDeclAsWritten(type));
-    CHECK_(class_decl && "TemplateSpecializationType is not a TplSpecDecl?");
+    const NamedDecl* named_decl = TypeToDeclAsWritten(type);
+    const ClassTemplateSpecializationDecl* class_decl = DynCastFrom(named_decl);
+
+    // Bail out if we are not a proper class
+    if (class_decl == nullptr) {
+      // If the template specialization decl is not sugar for a class, we
+      // expect it to be other kind of template decl, like a built-in.
```
Comment (kimgr) [inline iwyu.cc]: other kind -> some other kind (or maybe "another kind")

File: iwyu_output.cc (hunk 9 above)
Comment (kimgr) [reply iwyu_output.cc]: Either I'm misunderstanding your explanation or you've confused something above. As far as I can tell `isBuiltinFunc` returns true for any `f`-marked builtin, i.e. the ones that look like normal functions and require a header (e.g. memcpy). So your code is doing the right thing (if identifier has a non-zero builtin and name does not appear in libbuiltin-table, it must be a proper `__builtin_` builtin).

I think if we wanted to be fancy, we could do this lookup when reporting the use, and encode it as a use-flag, but I think this is fine as-is.
