### PR TITLE
Make sure C arrays result in includes and not a forward declaration

### LINKED ISSUE #1747: IWYU forward declares type used in array which causes compilation failure
If I have the following declaration in a header (C):

```
int sd_dhcp_server_set_lpr(sd_dhcp_server *server, const struct in_addr lpr[], size_t n);
```

Then IWYU chooses to forward declare `struct in_addr;`, which then causes the following compilation failure:

```
../src/systemd/sd-dhcp-server.h:72:47: error: array has incomplete element type 'const struct in_addr'
   72 |                 const struct in_addr addresses[],
      |                                               ^
../src/systemd/sd-dhcp-lease.h:30:8: note: forward declaration of 'struct in_addr'
   30 | struct in_addr;
```

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
If an array type is used in a function declaration, the full type has to be available, and not just a forward declaration.

Fixes #1747

### CODE REVIEW

**Comment by bolshakov-a** [comment]
> If an array type is used in a function declaration

Not only in a function declaration but also in an `extern` variable declaration, `typedef` declaration, under a pointer, or wherever:
```
$ ./clang -fsyntax-only -x c -
typedef struct Undef (*ArrayPtr)[5];

<stdin>:1:33: error: array has incomplete element type 'struct Undef'
    1 | typedef struct Undef (*ArrayPtr)[5];
      |                                 ^
<stdin>:1:16: note: forward declaration of 'struct Undef'
    1 | typedef struct Undef (*ArrayPtr)[5];
      |                ^
1 error generated.

$ ./clang -fsyntax-only -x c++ -
typedef struct Undef (*ArrayPtr)[5];

$
```
 Some of these cases are probably worth being placed in the test as well.

Also, please recall that the conventional way of writing tests for IWYU is to place the used stuff in an `-indirect.h` header to produce explicit diagnostics.

File: iwyu.cc [hunk 1]
```diff
@@ -2673,6 +2674,22 @@ class IwyuBaseAstVisitor : public BaseAstVisitor<Derived> {
...
 
+  bool VisitArrayType(ArrayType* type) {
+    if (CanIgnoreCurrentASTNode())
+      return true;
+    if (!compiler()->getLangOpts().CPlusPlus)
+      ReportTypeUse(CurrentLoc(), &*type->getElementType(), DerefKind::None);
+    return true;
+  }
+
+  bool VisitIncompleteArrayType(IncompleteArrayType *type) {
```
Comment (bolshakov-a) [inline iwyu.cc:2685]: What is it needed for? `IncompleteArrayType` is derived from `ArrayType`, so the previous handler should be sufficient.

Comment (DaanDeMeyer) [reply iwyu.cc:2685]: nvm turns out this isn't necessary after all

File: tests/c/array.c [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+//
+//===----------------------------------------------------------------------===//
+
+// IWYU_ARGS: -I .
+
+#include "tests/c/array-direct.h"
+
+// IWYU: Struct is defined in...*array-indirect.h
+// IWYU: Struct needs a declaration
+void array(const struct Struct array[]);
```
Comment (kimgr) [inline tests/c/array.c:16]: Since you just want an arbitrary struct type, you can use the reusable `struct Indirect` from `tests/c/direct.h`/`tests/c/indirect.h`.

I wrote up some design guidelines for tests: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUStyle.md#regression-tests, they may be useful.

File: iwyu.cc [hunk 3]
```diff
@@ -2673,6 +2673,14 @@ class IwyuBaseAstVisitor : public BaseAstVisitor<Derived> {
     return true;
   }
 
+  bool VisitArrayType(ArrayType* type) {
+    if (CanIgnoreCurrentASTNode())
+      return true;
+    if (!compiler()->getLangOpts().CPlusPlus)
+      ReportTypeUse(CurrentLoc(), &*type->getElementType(), DerefKind::None);
```
Comment (kimgr) [inline iwyu.cc:2680]: I think this would be clearer with a named variable;
```
const Type* elem_type = type->getElementType().getTypePtr();
ReportTypeUse(CurrentLoc(), elem_type, DerefKind::None);
```

**Comment by kimgr** [comment]
Looks great, thanks!

**Comment by bolshakov-a** [comment]
@DaanDeMeyer, thanks for the help with improving IWYU!
