### PR TITLE
Handle `UnaryTransformType`s in typedef decls

### LINKED ISSUE #169: Fails to see through std::remove_pointer
Originally reported on Google Code with ID 169

```
Put this code into a source file in tests/cxx:

traits_remove_pointer.cc:
#include <type_traits>                                                            

#include "tests/cxx/indirect.h"                                                   


std::remove_pointer<IndirectClass*>::type x;   

Run iwyu like so:

$ include-what-you-use -I. tests/cxx/traits_remove_pointer.cc

What is the expected output? What do you see instead?

This should produce no IWYU changes, but IWYU suggests that IndirectClass should be
forward-declared rather than included.

Issue found by Daniel Jump, reported on the mailing list.
```

Reported by `kim.grasman` on 2015-01-11 17:05:13

### PR DESCRIPTION
**Pull request by bolshakov-a**
In libc++, some type transformation templates are defined using `UnaryTransformType`s, approximately like this:
```cpp
template <typename T>
struct remove_pointer {
  using type = __remove_pointer(T);
};
```
It broke IWYU analysis of type provision because `UnaryTransformType` desugars to its canonical (output) type, hence `SubstTemplateTypeParmType` node was skipped in `IsSubstTemplateTypeParmType`, and the underlying type was considered as provided by the alias.

After this change, `UnaryTransformType` is replaced by its base (input) type on collecting typedef type components, thus preserving detection of `SubstTemplateTypeParmType`.

This fixes #169.

### CODE REVIEW

**Comment by bolshakov-a** [comment]
By the way, @kimgr, the bug test failed on the server not because of the bug but because the server has not libc++ installed. The same applies for tests for #300 and #1250.

File: iwyu_ast_util.cc [hunk 1]
```diff
@@ -722,6 +723,14 @@ class TypeEnumeratorWithoutSubstituted
   bool TraverseTypeHelper(QualType qual_type, bool traverse_qualifier) {
     CHECK_(!qual_type.isNull());
     const Type* type = qual_type.getTypePtr();
+
+    // UnaryTransformType desugars by default to its canonical type which,
```
Comment (kimgr) [inline iwyu_ast_util.cc]: Could you add a few examples of unary transforms, e.g. `A UnaryTransformType, such as __add_pointer or __remove_extents, desugars by default to its canonical type...`

File: iwyu_ast_util.h [hunk 2]
```diff
@@ -840,6 +840,10 @@ set<const clang::Type*> GetCanonicalComponentsOfType(const clang::Type* type);
 // template <class T> struct Tpl1 { typedef Tpl2<T, A> Alias; };
 // the returned set for the type 'Tpl1<B>::Alias' contains 'A' but not 'B'
 // or any sugar for 'B'.
+// This not necessarily returns all the complex components but should return at
```
Comment (kimgr) [inline iwyu_ast_util.h]: Phrasing: `This does not necessarily return all the ...`

Comment (bolshakov-a) [reply iwyu_ast_util.h]: Thanks!

**Comment by kimgr** [comment]
Looks great, thanks!
