### PR TITLE
Fix crash on construction inside unresolved call

### LINKED ISSUE #1434: IWYU crash: access violation
IWYU version: `include-what-you-use 0.22 (git:1f69a9a) based on clang version 18.0.0git (https://github.com/llvm/llvm-project 29f98d6c25e237d311038ce225f0b3109925d400)`

Given the following input:

```
//example.cpp
#include <variant>
#include <vector>
#include <map>

class test_t {
public:
    float* execute(std::variant<int, long long> var);
private:
    std::map<int, std::vector<float>> mpOrigins;
};

float* test_t::execute(std::variant<int, long long> var) {
    return std::visit([&](auto&& val) {
        return mpOrigins.emplace(val, std::vector<float>{}).first->second.data();
    }, var);
}
```
 `include-what-you-use.exe -std=c++20 example.cpp` crashes with non-zero exit code.
 
<details>
  <summary>Call stack</summary>

 ```
 >	include-what-you-use.exe!llvm::dyn_cast_if_present<clang::FunctionTemplateSpecializationInfo *,llvm::PointerUnion<clang::NamedDecl *,clang::MemberSpecializationInfo *,clang::FunctionTemplateSpecializationInfo *,clang::DependentFunctionTemplateSpecializationInfo *>>(const llvm::PointerUnion<clang::NamedDecl *,clang::MemberSpecializationInfo *,clang::FunctionTemplateSpecializationInfo *,clang::DependentFunctionTemplateSpecializationInfo *> & Val) Line 739	C++
 	[Inline Frame] include-what-you-use.exe!llvm::PointerUnion<clang::NamedDecl *,clang::MemberSpecializationInfo *,clang::FunctionTemplateSpecializationInfo *,clang::DependentFunctionTemplateSpecializationInfo *>::dyn_cast() Line 163	C++
 	include-what-you-use.exe!clang::FunctionDecl::getPrimaryTemplate() Line 4101	C++
 	include-what-you-use.exe!include_what_you_use::GetDefaultedArgResugarMap(const clang::FunctionDecl * decl) Line 917	C++
 	include-what-you-use.exe!include_what_you_use::GetTplInstDataForFunction(const clang::FunctionDecl * decl, const clang::Expr * calling_expr, std::function<std::set<clang::Type const *,std::less<clang::Type const *>,std::allocator<clang::Type const *>> __cdecl(clang::Type const *)> provided_getter) Line 1039	C++
 	[Inline Frame] include-what-you-use.exe!include_what_you_use::IwyuAstConsumer::GetTplInstData(const clang::FunctionDecl *) Line 4360	C++
 	include-what-you-use.exe!include_what_you_use::IwyuAstConsumer::SourceOrTargetTypeIsProvided(const include_what_you_use::ASTNode * construct_expr_node) Line 4336	C++
 	[Inline Frame] include-what-you-use.exe!include_what_you_use::IwyuBaseAstVisitor<include_what_you_use::IwyuAstConsumer>::HandleNonAutocastConstruction(clang::CXXConstructExpr *) Line 2745	C++
 	[Inline Frame] include-what-you-use.exe!include_what_you_use::IwyuBaseAstVisitor<include_what_you_use::IwyuAstConsumer>::VisitCXXConstructExpr(clang::CXXConstructExpr *) Line 2175	C++
 	[Inline Frame] include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::WalkUpFromCXXConstructExpr(clang::CXXConstructExpr *) Line 742	C++
 	[Inline Frame] include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::WalkUpFromCXXTemporaryObjectExpr(clang::CXXTemporaryObjectExpr *) Line 746	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXTemporaryObjectExpr(clang::CXXTemporaryObjectExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2644	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXTemporaryObjectExpr(clang::CXXTemporaryObjectExpr * expr) Line 762	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXBindTemporaryExpr(clang::CXXBindTemporaryExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2719	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2698	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * expr) Line 694	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXDependentScopeMemberExpr(clang::CXXDependentScopeMemberExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2410	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXDependentScopeMemberExpr(clang::CXXDependentScopeMemberExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2410	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXDependentScopeMemberExpr(clang::CXXDependentScopeMemberExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2410	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2698	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * expr) Line 694	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseExprWithCleanups(clang::ExprWithCleanups * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2733	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseReturnStmt(clang::ReturnStmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2404	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCompoundStmt(clang::CompoundStmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2368	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseFunctionHelper(clang::FunctionDecl * D) Line 2196	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXMethodDecl(clang::CXXMethodDecl * D) Line 2221	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * D) Line 242	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * decl) Line 384	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseFunctionTemplateDecl(clang::FunctionTemplateDecl * D) Line 1883	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * D) Line 518	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * decl) Line 384	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDeclContextHelper(clang::DeclContext * DC) Line 1478	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXRecordDecl(clang::CXXRecordDecl * D) Line 1994	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * D) Line 414	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * decl) Line 384	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseLambdaExpr(clang::LambdaExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2650	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseMaterializeTemporaryExpr(clang::MaterializeTemporaryExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2862	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2698	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCallExpr(clang::CallExpr * expr) Line 694	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseExprWithCleanups(clang::ExprWithCleanups * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2733	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseReturnStmt(clang::ReturnStmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2404	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCompoundStmt(clang::CompoundStmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 2368	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * S, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt *,1,bool,llvm::PointerLikeTypeTraits<clang::Stmt *>,llvm::PointerIntPairInfo<clang::Stmt *,1,llvm::PointerLikeTypeTraits<clang::Stmt *>>>> * Queue) Line 678	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseStmt(clang::Stmt * stmt) Line 398	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseFunctionHelper(clang::FunctionDecl * D) Line 2196	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseCXXMethodDecl(clang::CXXMethodDecl * D) Line 2221	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * D) Line 242	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * decl) Line 384	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDeclContextHelper(clang::DeclContext * DC) Line 1478	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl * D) Line 1578	C++
 	include-what-you-use.exe!clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * D) Line 752	C++
 	include-what-you-use.exe!include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl(clang::Decl * decl) Line 384	C++
 	include-what-you-use.exe!include_what_you_use::IwyuAstConsumer::HandleTranslationUnit(clang::ASTContext & context) Line 3729	C++
 	include-what-you-use.exe!clang::ParseAST(clang::Sema & S, bool PrintStats, bool SkipFunctionBodies) Line 183	C++
 	include-what-you-use.exe!clang::ASTFrontendAction::ExecuteAction() Line 1183	C++
 	include-what-you-use.exe!clang::FrontendAction::Execute() Line 1073	C++
 	include-what-you-use.exe!clang::CompilerInstance::ExecuteAction(clang::FrontendAction & Act) Line 1057	C++
 	include-what-you-use.exe!include_what_you_use::ExecuteAction(int argc, const char * * argv, std::function<std::unique_ptr<clang::FrontendAction,std::default_delete<clang::FrontendAction>> __cdecl(clang::driver::ToolChain const &)> make_iwyu_action) Line 344	C++
 	include-what-you-use.exe!main(int argc, char * * argv) Line 4466	C++
 	[External Code]	
 ```

</details>

[verbose_log.txt](https://github.com/include-what-you-use/include-what-you-use/files/13901408/verbose_log.txt)

The following change successfully exits:
```
//example.cpp
#include <variant>
#include <vector>
#include <map>

class test_t {
public:
    float* execute(std::variant<int, long long> var);
private:
    std::map<int, std::vector<float>> mpOrigins;
};

float* test_t::execute(std::variant<int, long long> var) {
    return std::visit([&](auto&& val) {
        auto v = std::vector<float>{};
        return mpOrigins.emplace(val, v).first->second.data();
    }, var);
}
```

Edit:
This also works fine:
```
#include <variant>
#include <vector>
#include <map>

class test_t {
public:
    float* execute(std::variant<int, long long> var);
private:
    std::map<int, std::vector<float>> mpOrigins;
};

float* test_t::execute(std::variant<int, long long> var) {
    return std::visit([&](auto&& val) {
        auto v = std::vector<float>{};
        return mpOrigins.emplace(val, std::move(v)).first->second.data();
    }, var);
}

```

### PR DESCRIPTION
**Pull request by bolshakov-a**
There is no callee for unresolved call expressions in template definitions.

This fixes #1434.

### CODE REVIEW

File: tests/cxx/implicit_ctor.cc [hunk 1]
```diff
@@ -112,6 +112,19 @@ void TestNonAutocastConstruction(const NoAutocastCtor& par) {
...
+  NonAggregate();
+};
+
+void OverloadedFn(int, NonAggregate);
+void OverloadedFn(float, NonAggregate);
+
+template <typename T>
+void TestNoCrashOnUnresolvedCall(T t) {
+  OverloadedFn(t, NonAggregate{});
+  t.SomeFn(NonAggregate{});
```
Comment (bolshakov-a) [inline tests/cxx/implicit_ctor.cc:125]: Not sure if this file is the correct place for these new test cases.

Comment (kimgr) [reply tests/cxx/implicit_ctor.cc:125]: Works for me!
