### PR TITLE
Fix handling of alias templates

### LINKED ISSUE #703: IWYU includes the wrong header for alias templates
Reduced test case:

test.cc:
```
#include "foo.hh"
#include <string>

int main() {
  Foo<std::string> foo;
}
```

foo.hh:
```
#pragma once

#include "bar.hh"

template <typename T>
using Foo = Bar<T, int>;
```

bar.hh:
```
#pragma once

template<typename T, typename U>
class Bar {
};
```

IWYU reports:
```
test.cc should add these lines:
#include "bar.hh"  // for Bar

test.cc should remove these lines:
- #include "foo.hh"  // lines 1-1

The full include-list for test.cc:
#include <string>  // for string
#include "bar.hh"  // for Bar
---
```

But following this advice would break compilation as Foo would no longer be found.

### PR DESCRIPTION
**Pull request by jbytheway**
When an alias template was used, IWYU would resolve it to the underlying aliased type rather than the template for the purposes of determining what header was required.  This led to incorrect header removals in some cases.  The test added in this PR demonstrates such a situation.

Fixes #703.

Fix that by splitting the `TypeToDeclAsWritten` into two functions: `TypeToDeclAsWritten` and `TypeToDeclForContent`.  The former is used for determining uses of the `Decl` itself, the latter is used for determining uses of the arguments passed to the template.

`TypeToDeclForContent` has the old behaviour of `TypeToDeclAsWritten` wheras the new `TypeToDeclAsWritten` prefers to report the alias template rather than the underlying `Decl`.

I only switched one call location to `TypeToDeclForContent`.  It's possible more should be changed, but this was the only one required to make the tests pass.  If you'd like me to try to review the other call sites then I can do so.

### CODE REVIEW

File: iwyu_ast_util.cc [hunk 1]
```diff
@@ -1207,7 +1208,7 @@ const Type* RemovePointersAndReferences(const Type* type) {
   return type;
 }
 
-const NamedDecl* TypeToDeclAsWritten(const Type* type) {
+static const NamedDecl* TypeToDeclImpl(const Type* type, bool AsWritten) {
```
Comment (kimgr) [inline iwyu_ast_util.cc]: `AsWritten` is LLVM style, IWYU uses `hacker_case` -- so please make this `as_written`

File: iwyu_ast_util.cc [hunk 2]
```diff
@@ -1245,6 +1255,14 @@ const NamedDecl* TypeToDeclAsWritten(const Type* type) {
   }
 }
 
+const NamedDecl* TypeToDeclAsWritten(const Type* type) {
+  return TypeToDeclImpl(type, true);
```
Comment (kimgr) [inline iwyu_ast_util.cc]: You could add a `/*as_written=*/true` here to make it clearer what the flag means. Cheapest form of named arguments.

File: iwyu_ast_util.cc [hunk 3]
```diff
@@ -1245,6 +1255,14 @@ const NamedDecl* TypeToDeclAsWritten(const Type* type) {
...
+}
+
+const NamedDecl* TypeToDeclForContent(const Type* type) {
+  return TypeToDeclImpl(type, false);
```
Comment (kimgr) [inline iwyu_ast_util.cc]: Named-arg comment for the Boolean literal.

File: iwyu_ast_util.cc (hunk 1 above)
Comment (jbytheway) [reply iwyu_ast_util.cc]: Fixed.

File: iwyu_ast_util.cc (hunk 2 above)
Comment (jbytheway) [reply iwyu_ast_util.cc]: Done.

File: iwyu_ast_util.cc (hunk 3 above)
Comment (jbytheway) [reply iwyu_ast_util.cc]: Done.

**Comment by kimgr** [comment]
Most appreciated!
